bind 0.0.0.0
protected-mode yes
port 0
tls-port 6379
tls-cert-file /run/redis/tls/redis.crt
tls-key-file /run/redis/tls/redis.key
tls-ca-cert-file /run/redis/tls/ca.crt
tls-auth-clients yes
tls-replication yes
tls-cluster yes
appendonly yes
appendfsync everysec
protected-mode yes
timeout 0
tcp-keepalive 300
maxmemory-policy noeviction
